name: Deploy to ECR

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main, actions]
  workflow_dispatch:
    
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
