name: Build and push images to Amazon ECR

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main, actions]
  workflow_dispatch:
    
jobs:
  build:
    name: Build and push Server image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build docker image
      run: mvn --batch-mode --update-snapshots -f ./server/pom.xml package

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: opencms
        IMAGE_TAG: latest
      run: | 
        IMAGE_NAME=$(docker images --format "{{.Repository}}" | grep '^molszewski' | head -n 1)
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $IMAGE_NAME
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
