name: Deploy to ECR

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main, actions]
  workflow_dispatch:
    
jobs:
  build:
    name: Build and push Server image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set working directory
      run: cd server
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build docker image
      run: mvn --batch-mode --update-snapshots package
